import { eq } from "drizzle-orm";

import { apiSettings, installSettings } from "@/settings";
import { insertAppInstall } from "@/utils/auth/AuthInstall";
import { Axios } from "@/utils/general/Axios";
import { getData } from "@/utils/general/Storage";
import { Toast } from "@/utils/general/Toast";
import { db } from "@/utils/sqlite/db";

import { collectAndStoreScanLocation } from "../location";
import { initScansTable, type InsertScanInput, type ScanLocation, scansTable } from "./init";

/* ------------------ BREAK ------------------ */

type InstallInfo = {
  id?: string;
};

type ScanApiResponse = {
  data?: InsertScanInput | null;
};

type LateLocationUpdateInput = {
  install_id: string;
  sync_status: "synced";
  location: ScanLocation;
};

/* ------------------ BREAK ------------------ */

const initialSyncPromises = new Map<string, Promise<boolean>>();
const initialLocationWaitMilliseconds = 3_000;

/* ------------------ BREAK ------------------ */

// Inserts a scan locally first and starts its initial API transfer without blocking navigation.
export async function insertScan(data: InsertScanInput) {
  if (!db) return null;

  try {
    await initScansTable();
    const installInfo = await resolveInstallInfo();
    const scanData: InsertScanInput = {
      ...data,
      install_id: data.install_id || installInfo?.id || null
    };
    const result = await db.insert(scansTable).values(scanData).run();
    const locationPromise = collectAndStoreScanLocation(scanData.id);
    const syncPromise = syncInitialScan(scanData, locationPromise);

    initialSyncPromises.set(scanData.id, syncPromise);
    void syncPromise.finally(() => initialSyncPromises.delete(scanData.id));

    return result;
  } catch (error: unknown) {
    const message = error instanceof Error ? error.message : "Unable to save this scan.";
    Toast.error({ message });
    console.error("Error inserting scan:", error);
    return null;
  };//try-catch ends
};//func ends

/* ------------------ BREAK ------------------ */

// Sends one scan row to the API using the UUID generated by the app.
export async function insertScanToAPI(data: InsertScanInput): Promise<InsertScanInput | null> {
  try {
    const apiUrl = apiSettings.getApiUrl({ path: "/app/scans" });
    const response = await Axios.post<ScanApiResponse>(apiUrl.href, data);
    return response.data?.data ?? null;
  } catch (error: unknown) {
    console.error("Error inserting scan to API:", error);
    return null;
  };//try-catch ends
};//func ends

/* ------------------ BREAK ------------------ */

// Waits for an in-flight initial POST so the final metadata PUT cannot overtake it.
export async function waitForInitialScanSync(id: string): Promise<boolean | null> {
  const syncPromise = initialSyncPromises.get(id);
  return syncPromise ? syncPromise : null;
};//func ends

/* ------------------ BREAK ------------------ */

// Updates local sync state after attempting the initial API POST.
async function syncInitialScan(
  data: InsertScanInput,
  locationPromise: ReturnType<typeof collectAndStoreScanLocation>
): Promise<boolean> {
  if (!db || !data.install_id) {
    await setLocalInitialSyncResult(data, null, "incomplete");
    return false;
  };//if ends

  const location = await getInitialScanLocation(locationPromise);
  const insertedScan = await insertScanToAPI({ ...data, location });
  const successfulStatus = data.type === "url" ? "processing" : "synced";
  await setLocalInitialSyncResult(data, insertedScan, insertedScan ? successfulStatus : "incomplete");

  if (insertedScan && data.type !== "url" && !location) {
    void syncLateNonWebScanLocation(data, locationPromise);
  };//if ends

  return Boolean(insertedScan);
};//func ends

// Resolves the stored install or creates it before a scan attempts synchronization.
async function resolveInstallInfo(): Promise<InstallInfo | null> {
  const storedInstallInfo = await getData({
    key: installSettings.storageKeys.installInfo.name
  }) as InstallInfo | null;

  if (storedInstallInfo?.id) return storedInstallInfo;

  const createdInstallInfo = await insertAppInstall() as InstallInfo | null;
  return createdInstallInfo?.id ? createdInstallInfo : null;
};//func ends

// Waits briefly for scan location without allowing it to block the initial API request indefinitely.
async function getInitialScanLocation(
  locationPromise: ReturnType<typeof collectAndStoreScanLocation>
): Promise<Awaited<ReturnType<typeof collectAndStoreScanLocation>>> {
  return new Promise((resolve) => {
    const timeout = setTimeout(() => resolve(null), initialLocationWaitMilliseconds);

    void locationPromise.then((location) => {
      clearTimeout(timeout);
      resolve(location);
    });
  });
};//func ends

// Sends a late-arriving location for non-web scans without entering the WebView completion flow.
async function syncLateNonWebScanLocation(
  scan: InsertScanInput,
  locationPromise: ReturnType<typeof collectAndStoreScanLocation>
): Promise<void> {
  const location = await locationPromise;

  if (!scan.install_id || !location) return;

  const updateData: LateLocationUpdateInput = {
    install_id: scan.install_id,
    sync_status: "synced",
    location
  };

  try {
    const apiUrl = apiSettings.getApiUrl({ path: `/app/scans/${scan.id}` });
    await Axios.put<ScanApiResponse>(apiUrl.href, updateData);
  } catch (error: unknown) {
    console.error("Error synchronizing late non-web scan location:", error);
  };//try-catch ends
};//func ends

// Persists the API-returned scan fields and initial synchronization result locally.
async function setLocalInitialSyncResult(
  localScan: InsertScanInput,
  insertedScan: InsertScanInput | null,
  syncStatus: InsertScanInput["sync_status"]
) {
  if (!db) return;

  await db
    .update(scansTable)
    .set({
      type: insertedScan?.type ?? localScan.type ?? null,
      status: insertedScan?.status ?? localScan.status ?? null,
      input_url: insertedScan?.input_url ?? localScan.input_url ?? null,
      final_url: insertedScan?.final_url ?? localScan.final_url ?? null,
      metadata: insertedScan?.metadata ?? localScan.metadata ?? null,
      sync_status: syncStatus,
      user_ip: insertedScan?.user_ip ?? null,
      updated_at: new Date().toISOString()
    })
    .where(eq(scansTable.id, localScan.id))
    .run();
};//func ends

/* ------------------ BREAK ------------------ */
