import { eq } from "drizzle-orm";

import { apiSettings, installSettings } from "@/settings";
import { insertAppInstall } from "@/utils/auth/AppInstall";
import { Axios } from "@/utils/general/Axios";
import { getData } from "@/utils/general/Storage";
import { Toast } from "@/utils/general/Toast";
import { db } from "@/utils/sqlite/db";

import { collectAndStoreScanLocation } from "../location";
import { getScanById } from "./getQueries";
import { initScansTable, type InsertScanInput, type ScanLocation, scansTable } from "./init";

/* ------------------ BREAK ------------------ */

type InstallInfo = {
  id?: string;
};

type ScanApiResponse = {
  data?: InsertScanInput | null;
};

type LateLocationUpdateInput = {
  install_id: string;
  sync_status: "synced";
  location: ScanLocation;
};

/* ------------------ BREAK ------------------ */

const initialSyncPromises = new Map<string, Promise<boolean>>();
const initialLocationWaitMilliseconds = 3_000;
const initialScanApiTimeoutMilliseconds = 10_000;

/* ------------------ BREAK ------------------ */

// Inserts a scan locally first and waits for its initial API attempt before opening the destination.
export async function insertScan(data: InsertScanInput) {
  if (!db) return null;

  try {
    await initScansTable();
    const installInfo = await resolveInstallInfo();
    const scanData: InsertScanInput = {
      ...data,
      install_id: data.install_id || installInfo?.id || null
    };
    const result = await db.insert(scansTable).values(scanData).run();
    const locationPromise = collectAndStoreScanLocation(scanData.id);
    const syncPromise = syncInitialScan(scanData, locationPromise);

    initialSyncPromises.set(scanData.id, syncPromise);
    void syncPromise.finally(() => initialSyncPromises.delete(scanData.id));
    await syncPromise;

    return result;
  } catch (error: unknown) {
    const message = error instanceof Error ? error.message : "Unable to save this scan.";
    Toast.error({ message });
    console.error("Error inserting scan:", error);
    return null;
  };//try-catch ends
};//func ends

/* ------------------ BREAK ------------------ */

// Sends one scan row to the API using the UUID generated by the app.
export async function insertScanToAPI(data: InsertScanInput): Promise<InsertScanInput | null> {
  try {
    const apiUrl = apiSettings.getApiUrl({ path: "/app/scans" });
    const response = await Axios.post<ScanApiResponse>(apiUrl.href, data, {
      timeout: initialScanApiTimeoutMilliseconds
    });
    const insertedScan = response.data?.data ?? null;

    if (insertedScan?.id !== data.id) {
      const errorMessage = `API returned scan ID ${insertedScan?.id || "none"} instead of ${data.id}.`;
      console.error(errorMessage, {
        expectedId: data.id,
        receivedId: insertedScan?.id || null
      });
      await appendScanError(data.id, errorMessage);
      return null;
    };//if ends

    return insertedScan;
  } catch (error: unknown) {
    await appendScanError(data.id, getErrorMessage(error));
    console.error("Error inserting scan to API:", error);
    return null;
  };//try-catch ends
};//func ends

/* ------------------ BREAK ------------------ */

// Waits for an in-flight initial POST so the final metadata PUT cannot overtake it.
export async function waitForInitialScanSync(id: string): Promise<boolean | null> {
  const syncPromise = initialSyncPromises.get(id);
  return syncPromise ? syncPromise : null;
};//func ends

/* ------------------ BREAK ------------------ */

// Waits for initial scan requests already running when the account is reset.
export async function waitForInitialScanSyncs(): Promise<void> {
  await Promise.allSettled([...initialSyncPromises.values()]);
};//export ends

// Updates local sync state after attempting the initial API POST.
async function syncInitialScan(
  data: InsertScanInput,
  locationPromise: ReturnType<typeof collectAndStoreScanLocation>
): Promise<boolean> {
  if (!db || !data.install_id) {
    await appendScanError(data.id, "The scan could not be sent because no installation ID was available.");
    await setLocalInitialSyncResult(data, null, "pending");
    return false;
  };//if ends

  const location = await getInitialScanLocation(locationPromise);
  const insertedScan = await insertScanToAPI({ ...data, location });
  const successfulStatus = data.type === "url" ? "processing" : "synced";
  await setLocalInitialSyncResult(data, insertedScan, insertedScan ? successfulStatus : "pending");

  if (insertedScan && data.type !== "url" && !location) {
    void syncLateNonWebScanLocation(data, locationPromise);
  };//if ends

  return Boolean(insertedScan);
};//func ends

// Resolves the stored install or creates it before a scan attempts synchronization.
async function resolveInstallInfo(): Promise<InstallInfo | null> {
  const storedInstallInfo = await getData({
    key: installSettings.storageKeys.installInfo.name
  }) as InstallInfo | null;

  if (storedInstallInfo?.id) return storedInstallInfo;

  const createdInstallInfo = await insertAppInstall() as InstallInfo | null;
  return createdInstallInfo?.id ? createdInstallInfo : null;
};//func ends

// Waits briefly for scan location without allowing it to block the initial API request indefinitely.
async function getInitialScanLocation(
  locationPromise: ReturnType<typeof collectAndStoreScanLocation>
): Promise<Awaited<ReturnType<typeof collectAndStoreScanLocation>>> {
  return new Promise((resolve) => {
    const timeout = setTimeout(() => resolve(null), initialLocationWaitMilliseconds);

    void locationPromise.then((location) => {
      clearTimeout(timeout);
      resolve(location);
    });
  });
};//func ends

// Sends a late-arriving location for non-web scans without entering the WebView completion flow.
async function syncLateNonWebScanLocation(
  scan: InsertScanInput,
  locationPromise: ReturnType<typeof collectAndStoreScanLocation>
): Promise<void> {
  const location = await locationPromise;

  if (!scan.install_id || !location) return;

  const updateData: LateLocationUpdateInput = {
    install_id: scan.install_id,
    sync_status: "synced",
    location
  };

  try {
    const apiUrl = apiSettings.getApiUrl({ path: `/app/scans/${scan.id}` });
    await Axios.put<ScanApiResponse>(apiUrl.href, updateData);
  } catch (error: unknown) {
    console.error("Error synchronizing late non-web scan location:", error);
  };//try-catch ends
};//func ends

// Persists the API-returned scan fields and initial synchronization result locally.
async function setLocalInitialSyncResult(
  localScan: InsertScanInput,
  insertedScan: InsertScanInput | null,
  syncStatus: InsertScanInput["sync_status"]
) {
  if (!db) return;

  const currentLocalScan = await getScanById(localScan.id);

  await db
    .update(scansTable)
    .set({
      value: insertedScan?.value ?? localScan.value,
      type: insertedScan?.type ?? localScan.type ?? null,
      kind: insertedScan?.kind ?? localScan.kind ?? localScan.type ?? null,
      status: insertedScan?.status ?? localScan.status ?? null,
      input_url: insertedScan?.input_url ?? localScan.input_url ?? null,
      final_url: insertedScan?.final_url ?? localScan.final_url ?? null,
      metadata: insertedScan?.metadata ?? localScan.metadata ?? null,
      sync_status: syncStatus,
      user_ip: insertedScan?.user_ip ?? null,
      location: insertedScan?.location ?? currentLocalScan?.location ?? localScan.location ?? null,
      user_id: insertedScan?.user_id ?? localScan.user_id ?? null,
      website_id: insertedScan?.website_id ?? localScan.website_id ?? null,
      install_id: insertedScan?.install_id ?? localScan.install_id ?? null,
      updated_at: insertedScan?.updated_at ?? new Date().toISOString()
    })
    .where(eq(scansTable.id, localScan.id))
    .run();
};//func ends

// Appends one timestamped failure line without replacing earlier scan errors.
export async function appendScanError(id: string, message: string): Promise<void> {
  if (!db) return;

  const currentScan = await getScanById(id);
  const errorLine = `[${new Date().toISOString()}] ${message.trim() || "Unknown scan synchronization error."}`;
  const nextError = currentScan?.error ? `${currentScan.error}\n${errorLine}` : errorLine;

  await db
    .update(scansTable)
    .set({ error: nextError })
    .where(eq(scansTable.id, id))
    .run();
};//func ends

// Converts an unknown thrown value into a concise persisted error message.
function getErrorMessage(error: unknown): string {
  return error instanceof Error ? error.message : "Unknown scan synchronization error.";
};//func ends

/* ------------------ BREAK ------------------ */
