import { eq } from "drizzle-orm";

import { apiSettings, installSettings } from "@/settings";
import { Axios } from "@/utils/general/Axios";
import { getData } from "@/utils/general/Storage";
import { Toast } from "@/utils/general/Toast";
import { db } from "@/utils/sqlite/db";

import { collectAndStoreScanLocation } from "../location";
import { initScansTable, type InsertScanInput, scansTable } from "./init";

/* ------------------ BREAK ------------------ */

type InstallInfo = {
  id?: string;
};

type ScanApiResponse = {
  data?: InsertScanInput | null;
};

/* ------------------ BREAK ------------------ */

const initialSyncPromises = new Map<string, Promise<boolean>>();

/* ------------------ BREAK ------------------ */

// Inserts a scan locally first and starts its initial API transfer without blocking navigation.
export async function insertScan(data: InsertScanInput) {
  if (!db) return null;

  try {
    await initScansTable();
    const installInfo = await getData({
      key: installSettings.storageKeys.installInfo.name
    }) as InstallInfo | null;
    const scanData: InsertScanInput = {
      ...data,
      install_id: data.install_id || installInfo?.id || null
    };
    const result = await db.insert(scansTable).values(scanData).run();
    const locationPromise = collectAndStoreScanLocation(scanData.id);
    const syncPromise = syncInitialScan(scanData, locationPromise);

    initialSyncPromises.set(scanData.id, syncPromise);
    void syncPromise.finally(() => initialSyncPromises.delete(scanData.id));

    return result;
  } catch (error: unknown) {
    const message = error instanceof Error ? error.message : "Unable to save this scan.";
    Toast.error({ message });
    console.error("Error inserting scan:", error);
    return null;
  };//try-catch ends
};//func ends

/* ------------------ BREAK ------------------ */

// Sends one scan row to the API using the UUID generated by the app.
export async function insertScanToAPI(data: InsertScanInput): Promise<InsertScanInput | null> {
  try {
    const apiUrl = apiSettings.getApiUrl({ path: "/app/scans" });
    const response = await Axios.post<ScanApiResponse>(apiUrl.href, data);
    return response.data?.data ?? null;
  } catch (error: unknown) {
    console.error("Error inserting scan to API:", error);
    return null;
  };//try-catch ends
};//func ends

/* ------------------ BREAK ------------------ */

// Waits for an in-flight initial POST so the final metadata PUT cannot overtake it.
export async function waitForInitialScanSync(id: string): Promise<boolean | null> {
  const syncPromise = initialSyncPromises.get(id);
  return syncPromise ? syncPromise : null;
};//func ends

/* ------------------ BREAK ------------------ */

// Updates local sync state after attempting the initial API POST.
async function syncInitialScan(
  data: InsertScanInput,
  locationPromise: ReturnType<typeof collectAndStoreScanLocation>
): Promise<boolean> {
  const location = await locationPromise;

  if (!db || !data.install_id) {
    await setLocalInitialSyncResult(data.id, "incomplete", null);
    return false;
  };//if ends

  const insertedScan = await insertScanToAPI({ ...data, location });
  const successfulStatus = data.sync_status === "synced" ? "synced" : "processing";
  await setLocalInitialSyncResult(
    data.id,
    insertedScan ? successfulStatus : "incomplete",
    insertedScan?.user_ip ?? null
  );
  return Boolean(insertedScan);
};//func ends

// Persists the initial sync state and server-observed IP without restarting synchronization.
async function setLocalInitialSyncResult(
  id: string,
  syncStatus: InsertScanInput["sync_status"],
  userIp: string | null
) {
  if (!db) return;

  await db
    .update(scansTable)
    .set({
      sync_status: syncStatus,
      user_ip: userIp,
      updated_at: new Date().toISOString()
    })
    .where(eq(scansTable.id, id))
    .run();
};//func ends

/* ------------------ BREAK ------------------ */
